version: '3'
services:
  eureka_8761:
    image: eureka:1.0.0-SNAPSHOT
    container_name: eureka_8761
    restart: "no"
    ports:
      - "8761:8761"
    environment:
      - EUREKA_SERVER=192.168.8.125
      - PORT=8761
      - GZ_IP=192.168.8.125
      - GZ_PORT=8762
      - SZ_IP=192.168.8.125
      - SZ_PORT=8762
  eureka_8762:
    image: eureka:1.0.0-SNAPSHOT
    container_name: eureka_8762
    restart: "no"
    ports:
      - "8762:8762"
    environment:
      - EUREKA_SERVER=192.168.8.125
      - PORT=8762
      - GZ_IP=192.168.8.125
      - GZ_PORT=8761
      - SZ_IP=192.168.8.125
      - SZ_PORT=8761