version: '3'
services:
  eureka_8761:
    image: eureka:1.0.0-SNAPSHOT
    container_name: eureka_8761
    restart: "no"
    ports:
      - "8761:8761"
    extra_hosts:
      - "work-ip:192.168.8.125"
    environment:
      - EUREKA_SERVER=192.168.8.125
      - GZ_IP=work-ip
      - GZ_PORT=8762
      - SZ_IP=work-ip
      - SZ_PORT=8762
#    links:
#      - "eureka_8762"
#    networks:
#      - eureka_net

  eureka_8762:
    image: eureka:1.0.0-SNAPSHOT
    container_name: eureka_8762
    restart: "no"
    ports:
      - "8762:8761"
    extra_hosts:
      - "work-ip:192.168.8.125"
    environment:
      - EUREKA_SERVER=192.168.8.125
      - GZ_IP=work-ip
      - GZ_PORT=8761
      - SZ_IP=work-ip
      - SZ_PORT=8761
#    links:
#      - "eureka_8761"
#    networks:
#      - eureka_net
#networks:
#  eureka_net:
#    driver: bridge