spring:
  profiles:
    active: @profileActive@
eureka:
  client:
    healthcheck:
      enabled: true #eureka.client.healthcheck.enabled=true should only be set in application.yml. Setting the value in bootstrap.yml causes undesirable side effects, such as registering in Eureka with an UNKNOWN status