spring:
  profiles:
     active: dev,swagger,database
  http:
    multipart:
      max-file-size: 20MB
      max-request-size: 50MB

  # logback配置参数
logging:
  config: classpath:config/logback-spring.xml
  level:
    root: debug

debug: false

server:
  connection-timeout: 60000