server:
  port: 30002
# mysql config
mysql:
  host: ${MYSQL_HOST:127.0.0.1}
  port: ${MYSQL_PORT:3306}
  dbname: ${MYSQL_DBNAME:sms}
  username: ${MYSQL_USERNAME:root}
#  password: ${MYSQL_PASSWORD:toor}
  password: ${MYSQL_PASSWORD:qiankun415}
#开启配置文件密文显示#
jasypt:
  encryptor:
    password: C2QNY7f7Co4Md7Bg