version: '3'
services:
  config_server:
    image: config_server:1.0.0-SNAPSHOT
    container_name: config_server
    restart: "no"
    ports:
      - "9999:9999"
    extra_hosts:
      - "work-ip:192.168.8.125"
    environment:
      - EUREKA_SERVER=work-ip
      - PORT=9999
      - GZ_IP=work-ip
      - GZ_PORT=8761
      - SZ_IP=work-ip
      - SZ_PORT=8762
      - APPNAME=config_server
      - RABBITMQ_HOST=work-ip
      - RABBITMQ_PORT=5672
      - RABBITMQ_USERNAME=guest
      - RABBITMQ_PASSWORD=guest