swagger:
  enable: true
  base-package: indi.ikun.spring
  path-regex: /error.*
  title: Global interface
  description: global interface
  version: 1.0.0
  url: http://localhost
  email: 1584114193@qq.com
  contact: 花有清香月有阴