spring:
  application:
    name: gateway
  profiles:
    active: ${PROFILES_ACTIVE:dev},ec
  main:
    banner-mode: log
  lifecycle:
    timeout-per-shutdown-phase: 30s #缓冲期
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
      routes:
        - id: security
          uri: lb://security
          predicates:
            - Path=/login
            - Path=/admin
            - Path=/index/info
#        - id: security2
#          uri: http://localhost:8086
#          predicates:
#            - Path=/index/info
#        - id: security3
#          uri: http://localhost:8086
#          predicates:
#            - Path=/index/meun


server:
  port: ${PORT:9997}

#eureka
eureka:
  client: #eureka客户端配置
    healthcheck:
      enabled: true #开启健康检查 eureka.client.healthcheck.enabled=true should only be set in application.yml. Setting the value in bootstrap.yml causes undesirable side effects, such as registering in Eureka with an UNKNOWN status