swagger: "2.0"
info:
  version: "1.0.0"
  title: "swagger definition for com.gzkit.service.ledger.officespace.api.OfficeSpaceApi"
  x-java-interface: "cse.gen.GZKIT_SHARE_SERVICES.property_ledger_service.OfficeSpaceApi.OfficeSpaceApiIntf"
basePath: "/api/officespace"
consumes:
- "application/json"
produces:
- "application/json"
paths:
  /v1/add:
    post:
      summary: "新增办公室面积台账"
      operationId: "add"
      consumes:
      - "application/json;charset=UTF-8"
      produces:
      - "application/json;charset=UTF-8"
      parameters:
      - in: "body"
        name: "officeSpaceVO"
        required: true
        schema:
          $ref: "#/definitions/OfficeSpaceVO"
      responses:
        200:
          description: "response of 200"
          schema:
            $ref: "#/definitions/DefaultResultBeanOfficeSpaceVO"
  /v1/delete/{id}:
    delete:
      summary: "删除办公室面积台账"
      operationId: "deleteById"
      consumes:
      - "application/json;charset=UTF-8"
      produces:
      - "application/json;charset=UTF-8"
      parameters:
      - name: "id"
        in: "path"
        description: "办公室面积台账id"
        required: true
        type: "string"
      responses:
        200:
          description: "response of 200"
          schema:
            $ref: "#/definitions/DefaultResultBean"
  /v1/getByPage:
    post:
      summary: "分页查询办公室面积台账接口"
      description: "分页查询办公室面积台账"
      operationId: "getByPage"
      consumes:
      - "application/json;charset=UTF-8"
      produces:
      - "application/json;charset=UTF-8"
      parameters:
      - in: "body"
        name: "pageQuery"
        required: true
        schema:
          $ref: "#/definitions/分页查询参数OfficeSpaceQuery"
      responses:
        200:
          description: "response of 200"
          schema:
            $ref: "#/definitions/DefaultResultBean"
  /v1/detail/{id}:
    get:
      summary: "办公室面积台账详情"
      operationId: "getDetailById"
      consumes:
      - "application/json;charset=UTF-8"
      produces:
      - "application/json;charset=UTF-8"
      parameters:
      - name: "id"
        in: "path"
        description: "办公室面积台账id"
        required: true
        type: "string"
      responses:
        200:
          description: "response of 200"
          schema:
            $ref: "#/definitions/DefaultResultBeanOfficeSpaceVO"
  /v1/update:
    put:
      summary: "修改办公室面积台账"
      operationId: "update"
      consumes:
      - "application/json;charset=UTF-8"
      produces:
      - "application/json;charset=UTF-8"
      parameters:
      - in: "body"
        name: "officeSpaceVO"
        required: true
        schema:
          $ref: "#/definitions/OfficeSpaceVO"
      responses:
        200:
          description: "response of 200"
          schema:
            $ref: "#/definitions/DefaultResultBeanOfficeSpaceVO"
definitions:
  OfficeSpaceVO:
    type: "object"
    properties:
      osId:
        type: "string"
        description: "主键id"
      osUnit:
        type: "string"
        description: "单位"
      osAddress:
        type: "string"
        description: "详细地址"
      osTotalArea:
        type: "number"
        format: "double"
        description: "总建筑面积"
      osOfficeArea:
        type: "number"
        format: "double"
        description: "办公使用面积"
      osDutyPersons:
        type: "number"
        format: "double"
        description: "在岗人数"
      osServiceArea:
        type: "number"
        format: "double"
        description: "服务用房面积"
      osDeviceArea:
        type: "number"
        format: "double"
        description: "设备用房面积"
      osAncillaryArea:
        type: "number"
        format: "double"
        description: "附属用房面积"
      remark:
        type: "string"
        description: "备注"
    x-java-class: "com.gzkit.service.ledger.officespace.vo.OfficeSpaceVO"
  DefaultResultBean:
    type: "object"
    properties:
      code:
        type: "integer"
        format: "int32"
      msg:
        type: "string"
      data:
        type: "object"
      extend:
        type: "object"
    x-java-class: "com.gzkit.service.core.bean.DefaultResultBean"
  DefaultResultBeanOfficeSpaceVO:
    type: "object"
    properties:
      code:
        type: "integer"
        format: "int32"
      msg:
        type: "string"
      data:
        $ref: "#/definitions/OfficeSpaceVO"
      extend:
        type: "object"
    x-java-class: "com.gzkit.service.core.bean.DefaultResultBean<com.gzkit.service.ledger.officespace.vo.OfficeSpaceVO>"
  OfficeSpaceQuery:
    type: "object"
    properties:
      osUnit:
        type: "string"
        description: "单位"
      osAddress:
        type: "string"
        description: "详细地址"
      remark:
        type: "string"
        description: "备注"
      osTotalArea:
        type: "number"
        format: "double"
        description: "总建筑面积"
      minOsTotalArea:
        type: "number"
        format: "double"
        description: "最小总建筑面积"
      maxOsTotalArea:
        type: "number"
        format: "double"
        description: "最大总建筑面积"
    x-java-class: "com.gzkit.service.ledger.officespace.vo.OfficeSpaceQuery"
  分页查询参数:
    type: "object"
    properties:
      pageNo:
        type: "integer"
        format: "int32"
        description: "页码"
      pageSize:
        type: "integer"
        format: "int32"
        description: "每页多少条"
      orderBy:
        type: "string"
        description: "排序字段和规则，可为空"
      condition:
        type: "object"
        description: "查询条件"
    x-java-class: "com.gzkit.service.spring.bean.PageQuery"
  分页查询参数OfficeSpaceQuery:
    type: "object"
    properties:
      pageNo:
        type: "integer"
        format: "int32"
        description: "页码"
      pageSize:
        type: "integer"
        format: "int32"
        description: "每页多少条"
      orderBy:
        type: "string"
        description: "排序字段和规则，可为空"
      condition:
        description: "查询条件"
        $ref: "#/definitions/OfficeSpaceQuery"
    x-java-class: "com.gzkit.service.spring.bean.PageQuery<com.gzkit.service.ledger.officespace.vo.OfficeSpaceQuery>"
