swagger: "2.0"
info:
  version: "1.0.0"
  title: "swagger definition for com.gzkit.service.ledger.property.api.PropertyApi"
  x-java-interface: "cse.gen.GZKIT_SHARE_SERVICES.property_ledger_service.PropertyApi.PropertyApiIntf"
basePath: "/api/property"
consumes:
- "application/json"
produces:
- "application/json"
paths:
  /v1/add:
    post:
      summary: "新增房产台账、土地台账"
      operationId: "add"
      consumes:
      - "application/json;charset=UTF-8"
      produces:
      - "application/json;charset=UTF-8"
      parameters:
      - in: "body"
        name: "propertyVO"
        required: true
        schema:
          $ref: "#/definitions/PropertyVO"
      responses:
        200:
          description: "response of 200"
          schema:
            $ref: "#/definitions/DefaultResultBeanPropertyVO"
  /v1/delete/{id}:
    delete:
      summary: "删除房产台账、土地台账"
      operationId: "deleteById"
      consumes:
      - "application/json;charset=UTF-8"
      produces:
      - "application/json;charset=UTF-8"
      parameters:
      - name: "id"
        in: "path"
        description: "物业id"
        required: true
        type: "string"
      responses:
        200:
          description: "response of 200"
          schema:
            $ref: "#/definitions/DefaultResultBean"
  /v1/getByPage:
    post:
      summary: "分页查询房产台账、土地台账接口"
      description: "分页查询房产台账、土地台账"
      operationId: "getByPage"
      consumes:
      - "application/json;charset=UTF-8"
      produces:
      - "application/json;charset=UTF-8"
      parameters:
      - in: "body"
        name: "pageQuery"
        required: true
        schema:
          $ref: "#/definitions/分页查询参数PropertyQuery"
      responses:
        200:
          description: "response of 200"
          schema:
            $ref: "#/definitions/DefaultResultBean"
  /v1/detail/{id}:
    get:
      summary: "房产台账、土地台账详情"
      operationId: "getDetailById"
      consumes:
      - "application/json;charset=UTF-8"
      produces:
      - "application/json;charset=UTF-8"
      parameters:
      - name: "id"
        in: "path"
        description: "物业id"
        required: true
        type: "string"
      responses:
        200:
          description: "response of 200"
          schema:
            $ref: "#/definitions/DefaultResultBeanPropertyVO"
  /v1/update:
    put:
      summary: "修改房产台账、土地台账"
      operationId: "update"
      consumes:
      - "application/json;charset=UTF-8"
      produces:
      - "application/json;charset=UTF-8"
      parameters:
      - in: "body"
        name: "propertyVO"
        required: true
        schema:
          $ref: "#/definitions/PropertyVO"
      responses:
        200:
          description: "response of 200"
          schema:
            $ref: "#/definitions/DefaultResultBeanPropertyVO"
definitions:
  PropertyVO:
    type: "object"
    properties:
      lhId:
        type: "string"
        description: "物业id"
      lhRegion:
        type: "string"
        description: "区域"
      lhNumber:
        type: "string"
        description: "编号"
      lhName:
        type: "string"
        description: "名称"
      landNo:
        type: "string"
        description: "土地证号"
      landUse:
        type: "string"
        description: "土地使用(保管）人"
      landUseproperty:
        type: "string"
        description: "土地使用性质"
      lhNouse:
        type: "string"
        description: "用途"
      lhNoarea:
        type: "string"
        description: "面积"
      landIfno:
        type: "string"
        description: "是否有土地证"
      lhLongitude:
        type: "number"
        format: "double"
        description: "经度"
      lhLatitude:
        type: "number"
        format: "double"
        description: "纬度"
      lhUseFlag:
        type: "string"
        description: "用途标记 1:办公2:住宅3:仓库4:变电站5:商铺6:配电房7:工业8:其他"
      homeBuildingfloor:
        type: "string"
        description: "房屋楼层"
      homeAddress:
        type: "string"
        description: "房产地址"
      homeUseunit:
        type: "string"
        description: "房产使用（保管）人"
      homeWarrant:
        type: "string"
        description: "房产权证"
      homeStatus:
        type: "string"
        description: "房产状态"
      homeLandnumber:
        type: "string"
        description: "房产土地编号"
      homePowernumber:
        type: "string"
        description: "房产用电户口"
      homeBuildingsource:
        type: "string"
        description: "房产建筑来源"
      homeCompletiondate:
        type: "string"
        format: "date-time"
        description: "房产竣工日期"
      homeBuildingstructure:
        type: "string"
        description: "房产建筑结构"
      homeCertificatenumber:
        type: "string"
        description: "房产证号"
      homePersoncharge:
        type: "string"
        description: "房产权属人"
      homeDateissue:
        type: "string"
        format: "date-time"
        description: "房产发证日期"
      homeConstructionunit:
        type: "string"
        description: "房产建设单位"
      homeDemo:
        type: "string"
        description: "房产备注"
      lhFlag:
        type: "string"
        description: "物业性质标记 1:房产2:土地"
      lhAddperson:
        type: "string"
        description: "物业新增人"
      lhUpdateperson:
        type: "string"
        description: "物业修改人"
      lhAdddate:
        type: "string"
        format: "date-time"
        description: "物业新增日期"
      lhUpdatedate:
        type: "string"
        format: "date-time"
        description: "物业修改日期"
      lhEconomicvalue:
        type: "string"
        description: "经济价值（高，中，低）"
      lhAssetvalue:
        type: "string"
        description: "资产价值"
      lhOperationvalue:
        type: "string"
        description: "运营价值"
      lhRisklevel:
        type: "string"
        description: "风险等级（高，中，低）/闲置风险"
      lhAdministration:
        type: "string"
        description: "本局管理单位"
      lhXianzmj:
        type: "string"
        description: "闲置面积"
      lhUtilizationrate:
        type: "string"
        description: "使用率"
      lhFireequipment:
        type: "string"
        description: "消防设备设施情况"
      lhFireinspection:
        type: "string"
        description: "消防验收情况"
      lhRiskdescription:
        type: "string"
        description: "风险描述"
      lhIssuehistory:
        type: "string"
        description: "历史遗留问题"
      lhManagement:
        type: "string"
        description: "处置措施"
      lhEmergencymanagement:
        type: "string"
        description: "应急处置措施"
      lhUsualname:
        type: "string"
        description: "惯用名"
      lhOwner:
        type: "string"
        description: "所属单位"
      lhFixed:
        type: "string"
        description: "是否固定资产"
      lhServiceLife:
        type: "string"
        description: "使用年限"
      lhCertificateStart:
        type: "string"
        format: "date-time"
        description: "证载开始使用日期"
      lhOwnership:
        type: "string"
        description: "资产所有权"
      lhCurrentUsage:
        type: "string"
        description: "现时用途"
      landGainType:
        type: "string"
        description: "土地获取方式"
      valueNo:
        type: "string"
        description: "资产卡片编号"
      valueName:
        type: "string"
        description: "资产卡片名称"
      valueType:
        type: "string"
        description: "资产分类"
      valueModel:
        type: "string"
        description: "规格型号"
      valueNumber:
        type: "string"
        description: "数量"
      valueUnit:
        type: "string"
        description: "计量单位"
      valueOriginal:
        type: "string"
        description: "资产原值"
      valueAccumulatedDepreciation:
        type: "string"
        description: "累计折旧"
      valueStart:
        type: "string"
        format: "date-time"
        description: "开始使用日期"
      valueLocation:
        type: "string"
        description: "坐落地点"
      valueDepartment:
        type: "string"
        description: "使用部门"
      valueRemark:
        type: "string"
        description: "备注"
      valueAccountEntry:
        type: "string"
        format: "date-time"
        description: "入账日期"
      valueHasCard:
        type: "string"
        description: "是否有资产卡片"
      valueDepreciableLives:
        type: "string"
        description: "折旧年限"
      valueDepreciableMethod:
        type: "string"
        description: "折旧方法"
      valueDepreciableRate:
        type: "string"
        description: "折旧率"
      valueNetSalvage:
        type: "string"
        description: "净残值率"
      valueNetWorth:
        type: "string"
        description: "净值"
      landOwner:
        type: "string"
        description: "土地证所有权人"
      landManager:
        type: "string"
        description: "权证管理人员"
      landHasCertificate:
        type: "string"
        description: "是否有产权证"
    x-java-class: "com.gzkit.service.ledger.property.vo.PropertyVO"
  DefaultResultBean:
    type: "object"
    properties:
      code:
        type: "integer"
        format: "int32"
      msg:
        type: "string"
      data:
        type: "object"
      extend:
        type: "object"
    x-java-class: "com.gzkit.service.core.bean.DefaultResultBean"
  DefaultResultBeanPropertyVO:
    type: "object"
    properties:
      code:
        type: "integer"
        format: "int32"
      msg:
        type: "string"
      data:
        $ref: "#/definitions/PropertyVO"
      extend:
        type: "object"
    x-java-class: "com.gzkit.service.core.bean.DefaultResultBean<com.gzkit.service.ledger.property.vo.PropertyVO>"
  PropertyQuery:
    type: "object"
    properties:
      lhRegion:
        type: "string"
        description: "区域"
      lhName:
        type: "string"
        description: "名称"
      homeBuildingfloor:
        type: "string"
        description: "用途标记 1:办公2:住宅3:仓库4:变电站5:商铺6:配电房7:工业8:其他"
      homeAddress:
        type: "string"
        description: "房产地址"
      homeStatus:
        type: "string"
        description: "房产状态"
      startHomeCompletiondate:
        type: "string"
        format: "date-time"
        description: "起始房产竣工日期"
      endHomeCompletiondate:
        type: "string"
        format: "date-time"
        description: "结束房产竣工日期"
      startHomeDateissue:
        type: "string"
        format: "date-time"
        description: "起始房产发证日期"
      endHomeDateissue:
        type: "string"
        format: "date-time"
        description: "结束房产发证日期"
      lhFlag:
        type: "string"
        description: "物业性质标记 1:房产2:土地"
      lhAddperson:
        type: "string"
        description: "物业新增人"
      lhUpdateperson:
        type: "string"
        description: "物业修改人"
      startLhAdddate:
        type: "string"
        format: "date-time"
        description: "物业起始新增日期"
      endLhAdddate:
        type: "string"
        format: "date-time"
        description: "物业结束新增日期"
      startLhUpdatedate:
        type: "string"
        format: "date-time"
        description: "物业起始修改日期"
      endLhUpdatedate:
        type: "string"
        format: "date-time"
        description: "物业起始修改日期"
      lhOwner:
        type: "string"
        description: "所属单位"
      lhFixed:
        type: "string"
        description: "是否固定资产"
      valueType:
        type: "string"
        description: "资产分类"
      valueLocation:
        type: "string"
        description: "坐落地点"
      valueDepartment:
        type: "string"
        description: "使用部门"
      startValueAccountEntry:
        type: "string"
        format: "date-time"
        description: "起始入账日期"
      endValueAccountEntry:
        type: "string"
        format: "date-time"
        description: "结束入账日期"
    x-java-class: "com.gzkit.service.ledger.property.vo.PropertyQuery"
  分页查询参数:
    type: "object"
    properties:
      pageNo:
        type: "integer"
        format: "int32"
        description: "页码"
      pageSize:
        type: "integer"
        format: "int32"
        description: "每页多少条"
      orderBy:
        type: "string"
        description: "排序字段和规则，可为空"
      condition:
        type: "object"
        description: "查询条件"
    x-java-class: "com.gzkit.service.spring.bean.PageQuery"
  分页查询参数PropertyQuery:
    type: "object"
    properties:
      pageNo:
        type: "integer"
        format: "int32"
        description: "页码"
      pageSize:
        type: "integer"
        format: "int32"
        description: "每页多少条"
      orderBy:
        type: "string"
        description: "排序字段和规则，可为空"
      condition:
        description: "查询条件"
        $ref: "#/definitions/PropertyQuery"
    x-java-class: "com.gzkit.service.spring.bean.PageQuery<com.gzkit.service.ledger.property.vo.PropertyQuery>"
