swagger: "2.0"
info:
  version: "1.0.0"
  title: "swagger definition for com.gzkit.service.ledger.revolvingroom.api.RevolvingRoomApi"
  x-java-interface: "cse.gen.GZKIT_SHARE_SERVICES.property_ledger_service.RevolvingRoomApi.RevolvingRoomApiIntf"
basePath: "/api/revolvingroom"
consumes:
- "application/json"
produces:
- "application/json"
paths:
  /v1/add:
    post:
      summary: "新增周转房台账"
      operationId: "add"
      consumes:
      - "application/json;charset=UTF-8"
      produces:
      - "application/json;charset=UTF-8"
      parameters:
      - in: "body"
        name: "revolvingRoomVO"
        required: true
        schema:
          $ref: "#/definitions/RevolvingRoomVO"
      responses:
        200:
          description: "response of 200"
          schema:
            $ref: "#/definitions/DefaultResultBeanRevolvingRoomVO"
  /v1/delete/{id}:
    delete:
      summary: "删除周转房台账"
      operationId: "deleteById"
      consumes:
      - "application/json;charset=UTF-8"
      produces:
      - "application/json;charset=UTF-8"
      parameters:
      - name: "id"
        in: "path"
        description: "id"
        required: true
        type: "string"
      responses:
        200:
          description: "response of 200"
          schema:
            $ref: "#/definitions/DefaultResultBean"
  /v1/getByPage:
    post:
      summary: "分页查询周转房台账接口"
      description: "分页查询周转房台账"
      operationId: "getByPage"
      consumes:
      - "application/json;charset=UTF-8"
      produces:
      - "application/json;charset=UTF-8"
      parameters:
      - in: "body"
        name: "pageQuery"
        required: true
        schema:
          $ref: "#/definitions/分页查询参数RevolvingRoomQuery"
      responses:
        200:
          description: "response of 200"
          schema:
            $ref: "#/definitions/DefaultResultBean"
  /v1/detail/{id}:
    get:
      summary: "周转房台账详情"
      operationId: "getDetailById"
      consumes:
      - "application/json;charset=UTF-8"
      produces:
      - "application/json;charset=UTF-8"
      parameters:
      - name: "id"
        in: "path"
        description: "id"
        required: true
        type: "string"
      responses:
        200:
          description: "response of 200"
          schema:
            $ref: "#/definitions/DefaultResultBeanRevolvingRoomVO"
  /v1/update:
    put:
      summary: "修改周转房台账"
      operationId: "update"
      consumes:
      - "application/json;charset=UTF-8"
      produces:
      - "application/json;charset=UTF-8"
      parameters:
      - in: "body"
        name: "revolvingRoomVO"
        required: true
        schema:
          $ref: "#/definitions/RevolvingRoomVO"
      responses:
        200:
          description: "response of 200"
          schema:
            $ref: "#/definitions/DefaultResultBeanRevolvingRoomVO"
definitions:
  RevolvingRoomVO:
    type: "object"
    properties:
      roomId:
        type: "string"
        description: "周转房主键"
      roomNumber:
        type: "string"
        description: "编号"
      roomUsecode:
        type: "string"
        description: "用途代码"
      roomName:
        type: "string"
        description: "名称"
      roomArea:
        type: "string"
        description: "建筑面积"
      roomType:
        type: "string"
        description: "结构类型"
      roomCompany:
        type: "string"
        description: "建筑单位"
      roomPattern:
        type: "string"
        description: "房屋格局"
      lesseePerson:
        type: "string"
        description: "承租人"
      lesseeIdentity:
        type: "string"
        description: "身份证"
      lesseePhone:
        type: "string"
        description: "联系电话"
      lesseeCompany:
        type: "string"
        description: "工作单位"
      lesseeNumber:
        type: "string"
        description: "合同编号"
      lesseeMoney:
        type: "number"
        format: "double"
        description: "房租"
      lesseeStartdate:
        type: "string"
        format: "date-time"
        description: "合同起始时间"
      lesseeEnddate:
        type: "string"
        format: "date-time"
        description: "合同到期时间"
      lesseeMoneytime:
        type: "string"
        description: "欠租情况"
      roomAddress:
        type: "string"
        description: "地址"
      roomAdddate:
        type: "string"
        format: "date-time"
        description: "新增时间"
      roomUpdatedate:
        type: "string"
        format: "date-time"
        description: "修改时间"
      roomUpdateperson:
        type: "string"
        description: "修改人"
      roomAddperson:
        type: "string"
        description: "新加人"
      roomContract:
        type: "string"
        description: "合同状态"
      roomRegion:
        type: "string"
        description: "区位"
      roomRenovation:
        type: "string"
        description: "是否装修"
      roomHousenumber:
        type: "string"
        description: "房号"
      roomBednumber:
        type: "string"
        description: "床号"
      roomOnenumber:
        type: "string"
        description: "单元号"
      roomHousebedflag:
        type: "string"
        description: "标记：1=房号，2=床号"
      roomHouseid:
        type: "string"
        description: "房id"
      roomIfhousbed:
        type: "string"
        description: "是否整屋出租"
      lesseeMoneytimedemo:
        type: "string"
        description: "欠租备注"
      roomOutarea:
        type: "string"
        description: "套内面积"
      roomPropernumber:
        type: "string"
        description: "物业台账编号"
      valueCard:
        type: "string"
        description: "资产卡片"
      valueOrigin:
        type: "number"
        format: "double"
        description: "资产原值"
    x-java-class: "com.gzkit.service.ledger.revolvingroom.vo.RevolvingRoomVO"
  DefaultResultBean:
    type: "object"
    properties:
      code:
        type: "integer"
        format: "int32"
      msg:
        type: "string"
      data:
        type: "object"
      extend:
        type: "object"
    x-java-class: "com.gzkit.service.core.bean.DefaultResultBean"
  DefaultResultBeanRevolvingRoomVO:
    type: "object"
    properties:
      code:
        type: "integer"
        format: "int32"
      msg:
        type: "string"
      data:
        $ref: "#/definitions/RevolvingRoomVO"
      extend:
        type: "object"
    x-java-class: "com.gzkit.service.core.bean.DefaultResultBean<com.gzkit.service.ledger.revolvingroom.vo.RevolvingRoomVO>"
  RevolvingRoomQuery:
    type: "object"
    properties:
      roomName:
        type: "string"
        description: "名称"
      roomType:
        type: "string"
        description: "结构类型"
      roomAddress:
        type: "string"
        description: "地址"
      startRoomAdddate:
        type: "string"
        format: "date-time"
        description: "起始新增时间"
      endRoomAdddate:
        type: "string"
        format: "date-time"
        description: "结束新增时间"
      startRoomUpdatedate:
        type: "string"
        format: "date-time"
        description: "起始修改时间"
      endRoomUpdatedate:
        type: "string"
        format: "date-time"
        description: "结束修改时间"
      roomUpdateperson:
        type: "string"
        description: "修改人"
      roomAddperson:
        type: "string"
        description: "新增人"
      roomContract:
        type: "string"
        description: "合同状态"
    x-java-class: "com.gzkit.service.ledger.revolvingroom.vo.RevolvingRoomQuery"
  分页查询参数:
    type: "object"
    properties:
      pageNo:
        type: "integer"
        format: "int32"
        description: "页码"
      pageSize:
        type: "integer"
        format: "int32"
        description: "每页多少条"
      orderBy:
        type: "string"
        description: "排序字段和规则，可为空"
      condition:
        type: "object"
        description: "查询条件"
    x-java-class: "com.gzkit.service.spring.bean.PageQuery"
  分页查询参数RevolvingRoomQuery:
    type: "object"
    properties:
      pageNo:
        type: "integer"
        format: "int32"
        description: "页码"
      pageSize:
        type: "integer"
        format: "int32"
        description: "每页多少条"
      orderBy:
        type: "string"
        description: "排序字段和规则，可为空"
      condition:
        description: "查询条件"
        $ref: "#/definitions/RevolvingRoomQuery"
    x-java-class: "com.gzkit.service.spring.bean.PageQuery<com.gzkit.service.ledger.revolvingroom.vo.RevolvingRoomQuery>"
