swagger: "2.0"
info:
  version: "1.0.0"
  title: "swagger definition for com.gzkit.service.ledger.substation.api.SubstationApi"
  x-java-interface: "cse.gen.GZKIT_SHARE_SERVICES.property_ledger_service.SubstationApi.SubstationApiIntf"
basePath: "/api/substation"
consumes:
- "application/json"
produces:
- "application/json"
paths:
  /v1/add:
    post:
      summary: "新增变电站"
      operationId: "add"
      consumes:
      - "application/json;charset=UTF-8"
      produces:
      - "application/json;charset=UTF-8"
      parameters:
      - in: "body"
        name: "substationVO"
        required: true
        schema:
          $ref: "#/definitions/SubstationVO"
      responses:
        200:
          description: "response of 200"
          schema:
            $ref: "#/definitions/DefaultResultBeanSubstationVO"
  /v1/delete/{id}:
    delete:
      summary: "删除变电站"
      operationId: "deleteById"
      consumes:
      - "application/json;charset=UTF-8"
      produces:
      - "application/json;charset=UTF-8"
      parameters:
      - name: "id"
        in: "path"
        description: "变电站id"
        required: true
        type: "string"
      responses:
        200:
          description: "response of 200"
          schema:
            $ref: "#/definitions/DefaultResultBean"
  /v1/getByPage:
    post:
      summary: "分页查询变电站"
      operationId: "findPage"
      consumes:
      - "application/json;charset=UTF-8"
      produces:
      - "application/json;charset=UTF-8"
      parameters:
      - in: "body"
        name: "query"
        required: true
        schema:
          $ref: "#/definitions/分页查询参数SubstationPageQuery"
      responses:
        200:
          description: "response of 200"
          schema:
            $ref: "#/definitions/DefaultResultBean"
  /v1/detail/{id}:
    get:
      summary: "变电站详情"
      operationId: "getDetailById"
      consumes:
      - "application/json;charset=UTF-8"
      produces:
      - "application/json;charset=UTF-8"
      parameters:
      - name: "id"
        in: "path"
        description: "变电站id"
        required: true
        type: "string"
      responses:
        200:
          description: "response of 200"
          schema:
            $ref: "#/definitions/DefaultResultBeanSubstationVO"
  /v1/update:
    put:
      summary: "修改变电站"
      operationId: "update"
      consumes:
      - "application/json;charset=UTF-8"
      produces:
      - "application/json;charset=UTF-8"
      parameters:
      - in: "body"
        name: "substationVO"
        required: true
        schema:
          $ref: "#/definitions/SubstationVO"
      responses:
        200:
          description: "response of 200"
          schema:
            $ref: "#/definitions/DefaultResultBeanSubstationVO"
definitions:
  SubstationVO:
    type: "object"
    properties:
      id:
        type: "string"
        description: "主键id"
      createName:
        type: "string"
        description: "创建人名称"
      createBy:
        type: "string"
        description: "创建人登录名称"
      createDate:
        type: "string"
        format: "date-time"
        description: "创建日期"
      updateName:
        type: "string"
        description: "更新人名称"
      updateBy:
        type: "string"
        description: "更新人登录名称"
      updateDate:
        type: "string"
        format: "date-time"
        description: "更新日期"
      sysOrgCode:
        type: "string"
        description: "所属部门"
      sysCompanyCode:
        type: "string"
        description: "所属公司"
      name:
        type: "string"
        description: "变电站"
      longitude:
        type: "string"
        description: "经度"
      latitude:
        type: "string"
        description: "纬度"
      owner:
        type: "string"
        description: "设备主人"
      ownerId:
        type: "string"
        description: "设备主人id"
      introduction:
        type: "string"
        description: "变电站简介"
      voltage:
        type: "string"
        description: "电压等级"
      department:
        type: "string"
        description: "所属巡维中心"
      shortName:
        type: "string"
        description: "简称"
      defaultScore:
        type: "number"
        format: "double"
        description: "司机默认分值"
      stationNum:
        type: "string"
        description: "站号:用于五方解锁，2个字符，且唯一"
      ktpId:
        type: "string"
        description: "康拓普id"
    x-java-class: "com.gzkit.service.ledger.substation.vo.SubstationVO"
  DefaultResultBean:
    type: "object"
    properties:
      code:
        type: "integer"
        format: "int32"
      msg:
        type: "string"
      data:
        type: "object"
      extend:
        type: "object"
    x-java-class: "com.gzkit.service.core.bean.DefaultResultBean"
  DefaultResultBeanSubstationVO:
    type: "object"
    properties:
      code:
        type: "integer"
        format: "int32"
      msg:
        type: "string"
      data:
        $ref: "#/definitions/SubstationVO"
      extend:
        type: "object"
    x-java-class: "com.gzkit.service.core.bean.DefaultResultBean<com.gzkit.service.ledger.substation.vo.SubstationVO>"
  SubstationPageQuery:
    type: "object"
    properties:
      name:
        type: "string"
        description: "变电站"
      owner:
        type: "string"
        description: "设备主人"
      voltage:
        type: "string"
        description: "电压等级"
      department:
        type: "string"
        description: "所属巡维中心"
    x-java-class: "com.gzkit.service.ledger.substation.vo.SubstationPageQuery"
  分页查询参数:
    type: "object"
    properties:
      pageNo:
        type: "integer"
        format: "int32"
        description: "页码"
      pageSize:
        type: "integer"
        format: "int32"
        description: "每页多少条"
      orderBy:
        type: "string"
        description: "排序字段和规则，可为空"
      condition:
        type: "object"
        description: "查询条件"
    x-java-class: "com.gzkit.service.spring.bean.PageQuery"
  分页查询参数SubstationPageQuery:
    type: "object"
    properties:
      pageNo:
        type: "integer"
        format: "int32"
        description: "页码"
      pageSize:
        type: "integer"
        format: "int32"
        description: "每页多少条"
      orderBy:
        type: "string"
        description: "排序字段和规则，可为空"
      condition:
        description: "查询条件"
        $ref: "#/definitions/SubstationPageQuery"
    x-java-class: "com.gzkit.service.spring.bean.PageQuery<com.gzkit.service.ledger.substation.vo.SubstationPageQuery>"
