spring:
  redis:
    host: 127.0.0.1
    port: 6379
    database: 0
    password: caddy
    timeout: 30000
    lettuce:  # 底层netty 多线程并发安全 jedis
      pool:
        #连接池最大连接数（使用负值表示没有限制）
        max-active: 8
        #连接池中的最大空闲连接
        max-idle: 8
        #连接池中的最小空闲连接
        min-idle: 0
        #连接池最大阻塞等待时间（使用负值表示没有限制）
        max-wait: 300
