server:
  port: 66
spring:
  application:
    name: spring boot demo

#-------系统监控工具相关,需要手动定制 在启动日志下可以看到很多端点 安全问题--------------------------#
management:
  security:
    enabled: false #false关闭/true开启默认 安全否则无法访问
  context-path: /manage #结合security 给监控工具做一些权限控制 http://127.0.0.1:8101/manage/bean
  port: 8181 #定制监控访问端口 如果是-1 则无法访问http://127.0.0.1:8181/manage/bean
endpoints:
  enabled: false #false关闭所有监控端点
  shutdown:
    enabled: true
  beans:
    id: mybean #定制id
    path: /bean #定制路径 http://127.0.0.1:8080/bean
    enabled: true #true开启，false关闭该端点
  dump:
    path: /du #定制路径 http://127.0.0.1:8080/du
    enabled: true
  health: #系统服务组件健康状态检测
    path: /h
    enabled: true
#-------系统监控工具相关,需要手动定制 在启动日志下可以看到很多端点 安全问题--------------------------#
jasypt:
  encryptor:
    password: m88CREAHperHSVG9q8sHJHaVwnr4xNlC #密钥
