swagger: "2.0"
info:
  version: "1.0.0"
  title: "swagger definition for com.gzkit.service.edge.wlb.order.emergencydemand.api.EmergencyDemandOrderApi"
  x-java-interface: "cse.gen.GZKIT_SHARE_SERVICES.assets_system_edge_service.EmergencyDemandOrderApi.EmergencyDemandOrderApiIntf"
basePath: "/api/v1/wlb"
consumes:
- "application/json"
produces:
- "application/json"
paths:
  /createEmergencyDemandOrder:
    post:
      summary: "生成紧急需求单接口"
      description: "物流宝根据现场要求生成紧急需求单到物资系统"
      operationId: "createEmergencyDemandOrder"
      consumes:
      - "application/json;charset=UTF-8"
      produces:
      - "application/json;charset=UTF-8"
      parameters:
      - in: "body"
        name: "emergencyDemandOrderVO"
        required: true
        schema:
          $ref: "#/definitions/EmergencyDemandOrderVO"
      responses:
        200:
          description: "response of 200"
          schema:
            $ref: "#/definitions/DefaultResultBean"
definitions:
  EmergencyDemandMaterialVO:
    type: "object"
    properties:
      materialId:
        type: "string"
        description: "物资品类id"
      vendor:
        type: "string"
        description: "供应商"
      vendorId:
        type: "string"
        description: "供应商id"
      reqQty:
        type: "number"
        description: "需求数量"
    x-java-class: "com.gzkit.service.edge.wlb.order.emergencydemand.vo.EmergencyDemandMaterialVO"
  EmergencyDemandOrderVO:
    type: "object"
    properties:
      reqType:
        type: "string"
        description: "需求类型(1项目物资申购 2备品申购 3零购固定资产 4储备物资申购  5 应急项目申购（这次生成的都回固定写为5)"
      isSpecial:
        type: "string"
        description: "是否特殊需求(1正常申购, 2特殊申购)"
      isEmergent:
        type: "string"
        description: "紧急需求单标识(0一般,1紧急, 2业扩工程)"
      isSingleSource:
        type: "string"
        description: "单一来源(1非单一来源申购, 2单一来源申购)"
      deptId:
        type: "string"
        description: "需求部门id"
      deptCode:
        type: "string"
        description: "需求部门编码"
      deptName:
        type: "string"
        description: "需求部门名称"
      creator:
        type: "string"
        description: "制单人名称"
      creatorId:
        type: "string"
        description: "制单人id"
      sunprojectName:
        type: "string"
        description: "子项目名称"
      subProjectId:
        type: "string"
        description: "子项目id"
      projectId:
        type: "string"
        description: "项目id"
      projectName:
        type: "string"
        description: "项目名称"
      remark:
        type: "string"
        description: "备注"
      materialVOList:
        type: "array"
        items:
          $ref: "#/definitions/EmergencyDemandMaterialVO"
    x-java-class: "com.gzkit.service.edge.wlb.order.emergencydemand.vo.EmergencyDemandOrderVO"
  DefaultResultBean:
    type: "object"
    properties:
      code:
        type: "integer"
        format: "int32"
      msg:
        type: "string"
      data:
        type: "object"
      extend:
        type: "object"
    x-java-class: "com.gzkit.service.core.bean.DefaultResultBean"
