swagger: "2.0"
info:
  version: "1.0.0"
  title: "swagger definition for com.gzkit.service.edge.biandian.formbasedata.api.FormBaseDataApi"
  x-java-interface: "cse.gen.GZKIT_SHARE_SERVICES.assets_system_edge_service.FormBaseDataApi.FormBaseDataApiIntf"
basePath: "/api/v1/biandian"
consumes:
- "application/json"
produces:
- "application/json"
paths:
  /getFormBaseData:
    post:
      summary: "表单基础数据下载接口"
      description: "获取输入参数为准的所在班组管理的所有作业表单模板及相关数据"
      operationId: "getFormBaseData"
      consumes:
      - "application/json;charset=UTF-8"
      produces:
      - "application/json;charset=UTF-8"
      parameters:
      - in: "body"
        name: "query"
        required: true
        schema:
          $ref: "#/definitions/CommonQuery"
      responses:
        200:
          description: "response of 200"
          schema:
            $ref: "#/definitions/DefaultResultBean"
definitions:
  CommonQuery:
    type: "object"
    properties:
      account:
        type: "string"
        description: "用户账号"
      password:
        type: "string"
        description: "用户密码（Base64 加密）"
      format:
        type: "string"
        description: "正文格式"
      content:
        type: "string"
        description: "终端请求的正文参数字符串，以XML格式呈现（Bae64编码）"
    x-java-class: "com.gzkit.service.edge.biandian.common.vo.CommonQuery"
  DefaultResultBean:
    type: "object"
    properties:
      code:
        type: "integer"
        format: "int32"
      msg:
        type: "string"
      data:
        type: "object"
      extend:
        type: "object"
    x-java-class: "com.gzkit.service.core.bean.DefaultResultBean"
