swagger: "2.0"
info:
  version: "1.0.0"
  title: "swagger definition for com.gzkit.service.edge.wlb.frameworkmaterial.api.FrameworkMaterialApi"
  x-java-interface: "cse.gen.GZKIT_SHARE_SERVICES.assets_system_edge_service.FrameworkMaterialApi.FrameworkMaterialApiIntf"
basePath: "/api/v1/wlb"
consumes:
- "application/json"
produces:
- "application/json"
paths:
  /getFrameMaterialDetail:
    post:
      summary: "框架物资明细查询接口"
      description: "框架物资明细查询接口"
      operationId: "getFrameMaterialDetail"
      consumes:
      - "application/json;charset=UTF-8"
      produces:
      - "application/json;charset=UTF-8"
      parameters:
      - in: "body"
        name: "query"
        required: true
        schema:
          $ref: "#/definitions/FrameworkMaterialQueryVO"
      responses:
        200:
          description: "response of 200"
          schema:
            $ref: "#/definitions/DefaultResultBean"
definitions:
  FrameworkMaterialQueryVO:
    type: "object"
    properties:
      materialId:
        type: "string"
        description: "物资id"
      materialName:
        type: "string"
        description: "物资名称"
      dataArea:
        type: "string"
        description: "数据区域，默认传0800"
    x-java-class: "com.gzkit.service.edge.wlb.frameworkmaterial.vo.FrameworkMaterialQueryVO"
  DefaultResultBean:
    type: "object"
    properties:
      code:
        type: "integer"
        format: "int32"
      msg:
        type: "string"
      data:
        type: "object"
      extend:
        type: "object"
    x-java-class: "com.gzkit.service.core.bean.DefaultResultBean"
