swagger: "2.0"
info:
  version: "1.0.0"
  title: "swagger definition for com.gzkit.service.edge.biandian.safetyactivity.api.SafetyActivityApi"
  x-java-interface: "cse.gen.GZKIT_SHARE_SERVICES.assets_system_edge_service.SafetyActivityApi.SafetyActivityApiIntf"
basePath: "/api/v1/biandian"
consumes:
- "application/json"
produces:
- "application/json"
paths:
  /deleteSafetyActivity:
    post:
      summary: "删除安全活动"
      description: "删除安全活动"
      operationId: "deleteSafetyActivity"
      consumes:
      - "application/json;charset=UTF-8"
      produces:
      - "application/json;charset=UTF-8"
      parameters:
      - in: "body"
        name: "sourceIds"
        required: true
        schema:
          $ref: "#/definitions/SourceIds"
      responses:
        200:
          description: "response of 200"
          schema:
            $ref: "#/definitions/DefaultResultBean"
  /saveSafetyActivity:
    post:
      summary: "新增或更新安全活动"
      description: "新增或更新安全活动"
      operationId: "saveSafetyActivity"
      consumes:
      - "application/json;charset=UTF-8"
      produces:
      - "application/json;charset=UTF-8"
      parameters:
      - in: "body"
        name: "safetyActivityVO"
        required: true
        schema:
          $ref: "#/definitions/SafetyActivityVO"
      responses:
        200:
          description: "response of 200"
          schema:
            $ref: "#/definitions/DefaultResultBean"
definitions:
  SourceIds:
    type: "object"
    properties:
      srcItem:
        type: "array"
        xml:
          namespace: "http://sp.soa.csg.cn/"
        items:
          type: "string"
    x-java-class: "com.gzkit.service.edge.biandian.safetyactivity.bean.delete.SourceIds"
  DefaultResultBean:
    type: "object"
    properties:
      code:
        type: "integer"
        format: "int32"
      msg:
        type: "string"
      data:
        type: "object"
      extend:
        type: "object"
    x-java-class: "com.gzkit.service.core.bean.DefaultResultBean"
  SafetyActivityActorVO:
    type: "object"
    properties:
      userId:
        type: "string"
        description: "用户id"
      userName:
        type: "string"
        description: "用户名"
    x-java-class: "com.gzkit.service.edge.biandian.safetyactivity.vo.SafetyActivityActorVO"
  SafetyActivityVO:
    type: "object"
    properties:
      id:
        type: "string"
        description: "主键id"
      bureauCode:
        type: "string"
        description: "局编码"
      bizTime:
        type: "string"
        description: "时间"
      bizLocation:
        type: "string"
        description: "地点"
      activityTheme:
        type: "string"
        description: "活动主题"
      absentPersonnelAndReason:
        type: "string"
        description: "缺席人员及缺席原因"
      existProblems:
        type: "string"
        description: "存在问题"
      rectification:
        type: "string"
        description: "整改情况"
      opinionOrRequirement:
        type: "string"
        description: "领导或专责参加学习时提出的意见或要求"
      superiorOpinionRequirement:
        type: "string"
        description: "上级领导或有关人员批阅意见"
      activityContent:
        type: "string"
        description: "活动内容"
      teamOid:
        type: "string"
        description: "班组id"
      mainDisFlag:
        type: "string"
        description: "主配网标识  1:主网；2：配网；3：主配网"
      createUid:
        type: "string"
        description: "创建人uid"
      createUname:
        type: "string"
        description: "创建人"
      anchorUser:
        description: "主持人"
        $ref: "#/definitions/SafetyActivityActorVO"
      recordUser:
        description: "记录人"
        $ref: "#/definitions/SafetyActivityActorVO"
      auditSignatureUser:
        description: "审核人"
        $ref: "#/definitions/SafetyActivityActorVO"
      participantUsers:
        type: "array"
        description: "参与人"
        items:
          $ref: "#/definitions/SafetyActivityActorVO"
    x-java-class: "com.gzkit.service.edge.biandian.safetyactivity.vo.SafetyActivityVO"
