swagger: "2.0"
info:
  version: "1.0.0"
  title: "swagger definition for com.gzkit.service.edge.wlb.order.shipment.api.ShipmentOrderApi"
  x-java-interface: "cse.gen.GZKIT_SHARE_SERVICES.assets_system_edge_service.ShipmentOrderApi.ShipmentOrderApiIntf"
basePath: "/api/v1/wlb"
consumes:
- "application/json"
produces:
- "application/json"
paths:
  /createShipmentOrder:
    post:
      summary: "回写承运商信息以及新建配送单接口"
      description: "物流宝向物资管理系统回写承运商信息以及新建配送单（紧急配送/非紧急配送类型）"
      operationId: "createShipmentOrder"
      consumes:
      - "application/json;charset=UTF-8"
      produces:
      - "application/json;charset=UTF-8"
      parameters:
      - in: "body"
        name: "shipmentOrderVO"
        required: true
        schema:
          $ref: "#/definitions/ShipmentOrderVO"
      responses:
        200:
          description: "response of 200"
          schema:
            $ref: "#/definitions/DefaultResultBean"
definitions:
  ShipmentOrderVO:
    type: "object"
    properties:
      billId:
        type: "string"
        description: "配送单号"
      billType:
        type: "string"
        description: "单据类型(1：移库2：出库)"
      dataArea:
        type: "string"
        description: "数据区域"
      creatorId:
        type: "string"
        description: "制单人id"
      shipmentType:
        type: "string"
        description: "配送单类型(1 紧急配送单 2 一般配送单)"
      needLifting:
        type: "string"
        description: "是否需要吊装(1，是；2，否)"
      reqDeliveryDate:
        type: "string"
        description: "要求送达时间(格式：yyyy-MM-dd HH:mm:ss)"
      fromWarehouseId:
        type: "string"
        description: "发货仓库id"
      fromAddr:
        type: "string"
        description: "发货地址"
      fromConectorId:
        type: "string"
        description: "发货联系人id"
      fromConectorPhone:
        type: "string"
        description: "发货联系人电话"
      toWarehouseId:
        type: "string"
        description: "收货仓库id(单据类型为1（移库）时必填，2（出库）为非必填)"
      receiverAddr:
        type: "string"
        description: "收货地址"
      receiverContactorId:
        type: "string"
        description: "收货联系人id"
      receiverContactorPhone:
        type: "string"
        description: "收货联系人电话"
      transportCosts:
        type: "number"
        description: "运输费用（元）"
      kilometers:
        type: "string"
        description: "配送距离（公里）"
      remark:
        type: "string"
        description: "备注"
      transVendorId:
        type: "string"
        description: "运输单位ID"
      transVendorName:
        type: "string"
        description: "运输单位名称"
      transportType:
        type: "string"
        description: "运输车型"
      transportLicense:
        type: "string"
        description: "运输车辆车牌号码"
      transportCondition:
        type: "string"
        description: "运输车辆车况"
      transportDriverid:
        type: "string"
        description: "运输司机id"
      transportDriver:
        type: "string"
        description: "运输司机姓名"
      transportDriverPhone:
        type: "string"
        description: "运输司机联系方式"
      carriersNum:
        type: "integer"
        format: "int32"
        description: "承运商装运人员数量"
      trainNum:
        type: "integer"
        format: "int32"
        description: "车次"
      objectId:
        type: "string"
        description: "单据id(急救包补货生成的移库单id/应急抢修生成的出库单id)"
    x-java-class: "com.gzkit.service.edge.wlb.order.shipment.vo.ShipmentOrderVO"
  DefaultResultBean:
    type: "object"
    properties:
      code:
        type: "integer"
        format: "int32"
      msg:
        type: "string"
      data:
        type: "object"
      extend:
        type: "object"
    x-java-class: "com.gzkit.service.core.bean.DefaultResultBean"
