spring:
  profiles:
    active: dev
  mvc:
    view:
      prefix: /
      suffix: .html
    async:
      request-timeout: 60000
  http:
    multipart:
      max-file-size: 20MB
      max-request-size: 50MB


# swagger配置参数
swagger:
  enable: true

  # logback配置参数
logging:
  config: classpath:config/logback-spring.xml
#沉浸式体验接口yml文件名

server:
  connection-timeout: 60000
