server:
  port: ${PORT:10001}

logging:
  level:
    root: info

eureka:
  instance:
    hostname: ${EUREKA_SERVER:localhost}
    appname: ${APPNAME:zipkin-server}
  client:
    service-url:
      gz:
        ip: ${GZ_IP:127.0.0.1}
        port: ${GZ_PORT:8761}
      sz:
        ip: ${SZ_IP:127.0.0.1}
        port: ${SZ_PORT:8762}