server:
  port: ${PORT:9999}

logging:
  level:
    root: warn

spring:
  rabbitmq:
    host: ${RABBITMQ_HOST:127.0.0.1}
    port: ${RABBITMQ_PORT:5672}
    username: ${RABBITMQ_USERNAME:guest}
    password: ${RABBITMQ_PASSWORD:guest}
eureka:
  instance:
    hostname: ${EUREKA_SERVER:localhost}
    appname: ${APPNAME:config_server}
  client:
    service-url:
      gz:
        ip: ${GZ_IP:127.0.0.1}
        port: ${GZ_PORT:8761}
      sz:
        ip: ${SZ_IP:127.0.0.1}
        port: ${SZ_PORT:8762}