spring:
  profiles:
     active: dev
  http:
    multipart:
      max-file-size: 20MB
      max-request-size: 50MB

  # logback配置参数
logging:
  config: classpath:config/logback-spring.xml

debug: false

server:
  connection-timeout: 60000
swagger:
  enable: true
  base-package: indi.ikun.spring.demo-springboot
  path-regex: /error.*
  title: demo Service API
  description: demo springboot
  version: 1.0.0
# 全局数据库配置 config
