server:
  port: 30002
  context-path: /dev
#h3bpm接口常量
h3bpm:
  #请求路径
  ip: 127.0.0.1
  port: 8088
  system-code: H3
  secret: Authine
  org-api: /Portal/org-api/rsa
  bpm-api: /Portal/bpm-api/rsa
  sso-api: /Portal/sso-api/rsa
  api:
    get:
      # 获取可发起流程 会返回Code供start-flow接口使用：workfownodes/administrator?systemCode=H3&secret=Authine&showFavorite=false&isMobile=false&userCode=administrator
      get-flow: /workfownodes
      #获取userid /userId/getBy?userCode= instanceid 通过start-flow接口获取
      get-userid: /userId/getBy
      #获取待办：USERID是通过workitems/unfinish/{USERID}?systemCode=H3&secret=Authine&startTime=2019-09-01&endTime=2019-09-30&startIndex=1&endIndex=1
      get-todos: /workitems/unfinish
    post:
      #发起流程：workflows/CODE   CODE是通过get-flow返回的data内的CODE 返回有instanceId，workItemID
      start-flow: /workflows
      #/instanceId/getBy/{workItemId}
      get-instanceid: /instanceId/getBy
      #上传文件
      uploadfile: /Upload/AttachmentFile
      #根据流程实例id获取bizObjectId /bizObjectId/getBy/{instanceId}
      get-bizobjectid: /bizObjectId/getBy
    put:
      #审批：submit/{workItemId} 参数涉及userid  workItemId
      approve: /workitems/submit
      # 驳回工作任务：workitems/returns/{workItemId}
      do-return: /workitems/returns
      #设置单个表单itemvalues/{keyName} 参数涉及bizObjectId
      inputform: /itemvalues
      # 激活指定节点，设置参与者
      activities: /addMultipleParticipants